package com.barran.gank.libs.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.barran.gank.libs.greendao.DataInfoEntity;

import com.barran.gank.libs.greendao.DataInfoEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dataInfoEntityDaoConfig;

    private final DataInfoEntityDao dataInfoEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dataInfoEntityDaoConfig = daoConfigMap.get(DataInfoEntityDao.class).clone();
        dataInfoEntityDaoConfig.initIdentityScope(type);

        dataInfoEntityDao = new DataInfoEntityDao(dataInfoEntityDaoConfig, this);

        registerDao(DataInfoEntity.class, dataInfoEntityDao);
    }
    
    public void clear() {
        dataInfoEntityDaoConfig.clearIdentityScope();
    }

    public DataInfoEntityDao getDataInfoEntityDao() {
        return dataInfoEntityDao;
    }

}
